# Generated by Django 5.0.14 on 2026-05-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('nursing', 'Nursing'), ('public_health', 'Public Health'), ('community_health', 'Community Health'), ('mental_health', 'Mental Health'), ('clinical', 'Clinical'), ('administrative', 'Administrative'), ('research', 'Research'), ('Elderly', 'Elderly'), ('Childcare', 'Childcare'), ('Disability', 'Disability'), ('Household', 'Household'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft'), ('Active', 'Active')], default='open', max_length=20),
        ),
    ]
