# Generated by Django 5.0.14 on 2026-05-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_application_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('portfolio', 'Portfolio'), ('cv', 'CV')], db_index=True, default='portfolio', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
