# Generated by Django 5.0.14 on 2026-05-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_application_application_type_application_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='cvs/'),
        ),
    ]
