# Generated by Django 5.0.14 on 2026-05-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_ticket_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='support/tickets/'),
        ),
    ]
