# Generated by Django 5.0.14 on 2026-05-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='back_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='kyc/back/'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='front_image',
            field=models.ImageField(max_length=500, upload_to='kyc/front/'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='selfie_image',
            field=models.ImageField(max_length=500, upload_to='kyc/selfie/'),
        ),
        migrations.AlterField(
            model_name='ngoprofile',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='ngo_logos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profiles/'),
        ),
    ]
